# Site settings
title: Vincent Knight
email: vincent.knight@gmail.com
description: "Personal webpage of Dr Vincent Knight. Mathematician at Cardiff University."
url: "http://vknight.org"
github_username: "drvinceknight"
twitter_username: "@drvinceknight"
plus_username: "+VincentKnight"

# Build settings
markdown: kramdown
permalink: pretty
highlighter: rouge
